const data =[
    {"TA Identifier": "ADIO", "TA Name": "hello", "Email Address": "test.tester@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "EFGH", "TA Name": "tester", "Email Address": "test.mctester@ymail.com", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "EFGH", "TA Name": "tester", "Email Address": "test.mctester@ymail.com", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "TXAG", "TA Name": "AI B User Test", "Email Address": "alvin.a.brunner@faa.gov", "Status": "active", "Tokens Submitted": 59},
    {"TA Identifier": "BDTC", "TA Name": "BigDaves Testing Center", "Email Address": "4355398+bdtc@gmail.com", "Status": "active", "Tokens Submitted": 10203},
    {"TA Identifier": "EFGH", "TA Name": "tester", "Email Address": "test.mctester@ymail.com", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "BRID", "TA Name": "Bridget Test Account", "Email Address": "bridget.ctr.ryan@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "CCCC", "TA Name": "file:\\c:\\boot.ini", "Email Address": "test.ctr.tester@yahoo.com", "Status": "inactive", "Tokens Submitted": 0},
    {"TA Identifier": "SKTF", "TA Name": "Srikanth Test FAA", "Email Address": "srikanth.ctr.kasi@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "SKTF", "TA Name": "Srikanth Test FAA", "Email Address": "srikanth.ctr.kasi@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "TXAG", "TA Name": "AI B User Test", "Email Address": "alvin.a.brunner@faa.gov", "Status": "active", "Tokens Submitted": 59},
    {"TA Identifier": "SKTF", "TA Name": "Srikanth Test FAA", "Email Address": "srikanth.ctr.kasi@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "CCCC", "TA Name": "file:\\c:\\boot.ini", "Email Address": "test.ctr.tester@yahoo.com", "Status": "inactive", "Tokens Submitted": 0},
    {"TA Identifier": "ADIO", "TA Name": "hello", "Email Address": "test.tester@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "SKTF", "TA Name": "Srikanth Test FAA", "Email Address": "srikanth.ctr.kasi@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "BRID", "TA Name": "Bridget Test Account", "Email Address": "bridget.ctr.ryan@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "BDTC", "TA Name": "BigDaves Testing Center", "Email Address": "4355398+bdtc@gmail.com", "Status": "active", "Tokens Submitted": 10203},
    {"TA Identifier": "TXAG", "TA Name": "AI B User Test", "Email Address": "alvin.a.brunner@faa.gov", "Status": "active", "Tokens Submitted": 59},
    {"TA Identifier": "SKTF", "TA Name": "Srikanth Test FAA", "Email Address": "srikanth.ctr.kasi@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "EFGH", "TA Name": "tester", "Email Address": "test.mctester@ymail.com", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "BDTC", "TA Name": "BigDaves Testing Center", "Email Address": "4355398+bdtc@gmail.com", "Status": "active", "Tokens Submitted": 10203},
    {"TA Identifier": "TXAG", "TA Name": "AI B User Test", "Email Address": "alvin.a.brunner@faa.gov", "Status": "active", "Tokens Submitted": 59},
    {"TA Identifier": "TXAG", "TA Name": "AI B User Test", "Email Address": "alvin.a.brunner@faa.gov", "Status": "active", "Tokens Submitted": 59},
    {"TA Identifier": "ADIO", "TA Name": "hello", "Email Address": "test.tester@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "CCCC", "TA Name": "file:\\c:\\boot.ini", "Email Address": "test.ctr.tester@yahoo.com", "Status": "inactive", "Tokens Submitted": 0},
    {"TA Identifier": "DHPP", "TA Name": "DHPP", "Email Address": "4355398+dhpp@gmail.com", "Status": "inactive", "Tokens Submitted": 7},
    {"TA Identifier": "CCCC", "TA Name": "file:\\c:\\boot.ini", "Email Address": "test.ctr.tester@yahoo.com", "Status": "inactive", "Tokens Submitted": 0},
    {"TA Identifier": "ADIO", "TA Name": "hello", "Email Address": "test.tester@faa.gov", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "TXAG", "TA Name": "AI B User Test", "Email Address": "alvin.a.brunner@faa.gov", "Status": "active", "Tokens Submitted": 59},
    {"TA Identifier": "EFGH", "TA Name": "tester", "Email Address": "test.mctester@ymail.com", "Status": "active", "Tokens Submitted": 0},
    {"TA Identifier": "XPLR", "TA Name": "Explorer Testing", "Email Address": "explorer.testing@faa.gov", "Status": "active", "Tokens Submitted": 12},
  {"TA Identifier": "MNKP", "TA Name": "Manikanta Test", "Email Address": "manikanta.test@faa.gov", "Status": "inactive", "Tokens Submitted": 5},
  {"TA Identifier": "JNDO", "TA Name": "John Doe", "Email Address": "john.doe@faa.gov", "Status": "active", "Tokens Submitted": 100},
  {"TA Identifier": "MKLS", "TA Name": "Mock Labs", "Email Address": "mock.labs@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "GHJK", "TA Name": "Gamma HJK", "Email Address": "gamma.hjk@faa.gov", "Status": "active", "Tokens Submitted": 23},
  {"TA Identifier": "PQRX", "TA Name": "PQRX Testing Center", "Email Address": "pqrxtest@faa.gov", "Status": "active", "Tokens Submitted": 50},
  {"TA Identifier": "LMNT", "TA Name": "Element Testing", "Email Address": "element.testing@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "UVWX", "TA Name": "UVWX Services", "Email Address": "services.uvwx@faa.gov", "Status": "active", "Tokens Submitted": 7},
  {"TA Identifier": "YZAA", "TA Name": "Alpha Test", "Email Address": "alpha.test@faa.gov", "Status": "active", "Tokens Submitted": 98},
  {"TA Identifier": "BETA", "TA Name": "Beta Group", "Email Address": "beta.group@faa.gov", "Status": "inactive", "Tokens Submitted": 3},
  {"TA Identifier": "TEST", "TA Name": "Test Center 1", "Email Address": "test.center1@faa.gov", "Status": "active", "Tokens Submitted": 32},
  {"TA Identifier": "DXYZ", "TA Name": "Delta XYZ", "Email Address": "delta.xyz@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "QWER", "TA Name": "QWER Center", "Email Address": "qwer.center@faa.gov", "Status": "active", "Tokens Submitted": 67},
  {"TA Identifier": "TYUI", "TA Name": "Test YUI", "Email Address": "test.yui@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "LKJH", "TA Name": "LKJH Research", "Email Address": "lkjh.research@faa.gov", "Status": "active", "Tokens Submitted": 12},
  {"TA Identifier": "MNBV", "TA Name": "MNBV Team", "Email Address": "mnbv.team@faa.gov", "Status": "active", "Tokens Submitted": 54},
  {"TA Identifier": "ASDF", "TA Name": "ASDF Group", "Email Address": "asdf.group@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "ZXCV", "TA Name": "ZXCV Testers", "Email Address": "zxcv.testers@faa.gov", "Status": "active", "Tokens Submitted": 3},
  {"TA Identifier": "VCXZ", "TA Name": "VCXZ Members", "Email Address": "vczx.members@faa.gov", "Status": "active", "Tokens Submitted": 2},
  {"TA Identifier": "NBHG", "TA Name": "NBHG Unit", "Email Address": "nbhg.unit@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "MNKP", "TA Name": "Manikanta Test", "Email Address": "manikanta.test@faa.gov", "Status": "inactive", "Tokens Submitted": 5},
  {"TA Identifier": "JNDO", "TA Name": "John Doe", "Email Address": "john.doe@faa.gov", "Status": "active", "Tokens Submitted": 100},
  {"TA Identifier": "MKLS", "TA Name": "Mock Labs", "Email Address": "mock.labs@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "GHJK", "TA Name": "Gamma HJK", "Email Address": "gamma.hjk@faa.gov", "Status": "active", "Tokens Submitted": 23},
  {"TA Identifier": "PQRX", "TA Name": "PQRX Testing Center", "Email Address": "pqrxtest@faa.gov", "Status": "active", "Tokens Submitted": 50},
  {"TA Identifier": "LMNT", "TA Name": "Element Testing", "Email Address": "element.testing@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "UVWX", "TA Name": "UVWX Services", "Email Address": "services.uvwx@faa.gov", "Status": "active", "Tokens Submitted": 7},
  {"TA Identifier": "YZAA", "TA Name": "Alpha Test", "Email Address": "alpha.test@faa.gov", "Status": "active", "Tokens Submitted": 98},
  {"TA Identifier": "BETA", "TA Name": "Beta Group", "Email Address": "beta.group@faa.gov", "Status": "inactive", "Tokens Submitted": 3},
  {"TA Identifier": "TEST", "TA Name": "Test Center 1", "Email Address": "test.center1@faa.gov", "Status": "active", "Tokens Submitted": 32},
  {"TA Identifier": "DXYZ", "TA Name": "Delta XYZ", "Email Address": "delta.xyz@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "QWER", "TA Name": "QWER Center", "Email Address": "qwer.center@faa.gov", "Status": "active", "Tokens Submitted": 67},
  {"TA Identifier": "TYUI", "TA Name": "Test YUI", "Email Address": "test.yui@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "LKJH", "TA Name": "LKJH Research", "Email Address": "lkjh.research@faa.gov", "Status": "active", "Tokens Submitted": 12},
  {"TA Identifier": "MNBV", "TA Name": "MNBV Team", "Email Address": "mnbv.team@faa.gov", "Status": "active", "Tokens Submitted": 54},
  {"TA Identifier": "ASDF", "TA Name": "ASDF Group", "Email Address": "asdf.group@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "ZXCV", "TA Name": "ZXCV Testers", "Email Address": "zxcv.testers@faa.gov", "Status": "active", "Tokens Submitted": 3},
  {"TA Identifier": "VCXZ", "TA Name": "VCXZ Members", "Email Address": "vczx.members@faa.gov", "Status": "active", "Tokens Submitted": 2},
  {"TA Identifier": "NBHG", "TA Name": "NBHG Unit", "Email Address": "nbhg.unit@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "MNKP", "TA Name": "Manikanta Test", "Email Address": "manikanta.test@faa.gov", "Status": "inactive", "Tokens Submitted": 5},
  {"TA Identifier": "JNDO", "TA Name": "John Doe", "Email Address": "john.doe@faa.gov", "Status": "active", "Tokens Submitted": 100},
  {"TA Identifier": "MKLS", "TA Name": "Mock Labs", "Email Address": "mock.labs@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "GHJK", "TA Name": "Gamma HJK", "Email Address": "gamma.hjk@faa.gov", "Status": "active", "Tokens Submitted": 23},
  {"TA Identifier": "PQRX", "TA Name": "PQRX Testing Center", "Email Address": "pqrxtest@faa.gov", "Status": "active", "Tokens Submitted": 50},
  {"TA Identifier": "LMNT", "TA Name": "Element Testing", "Email Address": "element.testing@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "UVWX", "TA Name": "UVWX Services", "Email Address": "services.uvwx@faa.gov", "Status": "active", "Tokens Submitted": 7},
  {"TA Identifier": "YZAA", "TA Name": "Alpha Test", "Email Address": "alpha.test@faa.gov", "Status": "active", "Tokens Submitted": 98},
  {"TA Identifier": "BETA", "TA Name": "Beta Group", "Email Address": "beta.group@faa.gov", "Status": "inactive", "Tokens Submitted": 3},
  {"TA Identifier": "TEST", "TA Name": "Test Center 1", "Email Address": "test.center1@faa.gov", "Status": "active", "Tokens Submitted": 32},
  {"TA Identifier": "DXYZ", "TA Name": "Delta XYZ", "Email Address": "delta.xyz@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "QWER", "TA Name": "QWER Center", "Email Address": "qwer.center@faa.gov", "Status": "active", "Tokens Submitted": 67},
  {"TA Identifier": "TYUI", "TA Name": "Test YUI", "Email Address": "test.yui@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "LKJH", "TA Name": "LKJH Research", "Email Address": "lkjh.research@faa.gov", "Status": "active", "Tokens Submitted": 12},
  {"TA Identifier": "MNBV", "TA Name": "MNBV Team", "Email Address": "mnbv.team@faa.gov", "Status": "active", "Tokens Submitted": 54},
  {"TA Identifier": "ASDF", "TA Name": "ASDF Group", "Email Address": "asdf.group@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "ZXCV", "TA Name": "ZXCV Testers", "Email Address": "zxcv.testers@faa.gov", "Status": "active", "Tokens Submitted": 3},
  {"TA Identifier": "VCXZ", "TA Name": "VCXZ Members", "Email Address": "vczx.members@faa.gov", "Status": "active", "Tokens Submitted": 2},
  {"TA Identifier": "NBHG", "TA Name": "NBHG Unit", "Email Address": "nbhg.unit@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "MNKP", "TA Name": "Manikanta Test", "Email Address": "manikanta.test@faa.gov", "Status": "inactive", "Tokens Submitted": 5},
  {"TA Identifier": "JNDO", "TA Name": "John Doe", "Email Address": "john.doe@faa.gov", "Status": "active", "Tokens Submitted": 100},
  {"TA Identifier": "MKLS", "TA Name": "Mock Labs", "Email Address": "mock.labs@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "GHJK", "TA Name": "Gamma HJK", "Email Address": "gamma.hjk@faa.gov", "Status": "active", "Tokens Submitted": 23},
  {"TA Identifier": "PQRX", "TA Name": "PQRX Testing Center", "Email Address": "pqrxtest@faa.gov", "Status": "active", "Tokens Submitted": 50},
  {"TA Identifier": "LMNT", "TA Name": "Element Testing", "Email Address": "element.testing@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "UVWX", "TA Name": "UVWX Services", "Email Address": "services.uvwx@faa.gov", "Status": "active", "Tokens Submitted": 7},
  {"TA Identifier": "YZAA", "TA Name": "Alpha Test", "Email Address": "alpha.test@faa.gov", "Status": "active", "Tokens Submitted": 98},
  {"TA Identifier": "BETA", "TA Name": "Beta Group", "Email Address": "beta.group@faa.gov", "Status": "inactive", "Tokens Submitted": 3},
  {"TA Identifier": "TEST", "TA Name": "Test Center 1", "Email Address": "test.center1@faa.gov", "Status": "active", "Tokens Submitted": 32},
  {"TA Identifier": "DXYZ", "TA Name": "Delta XYZ", "Email Address": "delta.xyz@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "QWER", "TA Name": "QWER Center", "Email Address": "qwer.center@faa.gov", "Status": "active", "Tokens Submitted": 67},
  {"TA Identifier": "TYUI", "TA Name": "Test YUI", "Email Address": "test.yui@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "LKJH", "TA Name": "LKJH Research", "Email Address": "lkjh.research@faa.gov", "Status": "active", "Tokens Submitted": 12},
  {"TA Identifier": "MNBV", "TA Name": "MNBV Team", "Email Address": "mnbv.team@faa.gov", "Status": "active", "Tokens Submitted": 54},
  {"TA Identifier": "ASDF", "TA Name": "ASDF Group", "Email Address": "asdf.group@faa.gov", "Status": "inactive", "Tokens Submitted": 0},
  {"TA Identifier": "ZXCV", "TA Name": "ZXCV Testers", "Email Address": "zxcv.testers@faa.gov", "Status": "active", "Tokens Submitted": 3},
  {"TA Identifier": "VCXZ", "TA Name": "VCXZ Members", "Email Address": "vczx.members@faa.gov", "Status": "active", "Tokens Submitted": 2},
  {"TA Identifier": "NBHG", "TA Name": "NBHG Unit", "Email Address": "nbhg.unit@faa.gov", "Status": "inactive", "Tokens Submitted": 0}
  ]

export default data;